quarkus.application.name=moodmatch-backend

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-migration-naming=true

%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/moodmatch
%dev.quarkus.datasource.username=moodmatch
%dev.quarkus.datasource.password=moodmatch

%test.quarkus.datasource.devservices.enabled=false
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:moodmatch;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa

%dev.quarkus.log.category."com.moodmatch".level=DEBUG
%test.quarkus.log.category."com.moodmatch".level=DEBUG
